spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/pdt"   # change local database
    username: pdt       # change local username
    password: paf2023   # change local password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create # none, update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy