logging:
  level:
    root: INFO

spring:
  application:
    name: ^project.name^
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    properties:
      hibernate:
        globally_quoted_identifiers: true

app:
  version: ^project.version^
  picture-config:
    picture-path: pictures
    store-in: memory
  translator-config:
    api-config:
      deepl-api-key: ${PDT_DEEPL_API_KEY}
      google-cloud-api-key: ${PDT_GOOGLE_CLOUD_API_KEY}
      google-clout-api-project: "bht-product-data-translation"
      microsoft-api-key: ${PDT_MICROSOFT_API_KEY}
      microsoft-api-region: "westeurope"
      currency-layer-api-key: ${PDT_CURRENCY_LAYER_API_KEY}
    factory: "StrategyTranslatorFactory"
    translator: "StrategyTranslator"
    strategy-config:
      text-translation-strategy: "GoogleWebTranslationStrategy"
      currency-conversion-strategy: "CurrencyLayerConversionStrategy"
      measurement-conversion-strategy: "LocalMeasurementConversionStrategy"
